Feature/support new flips
Coflnet/SkyblockMod pull request #47
Opened 2022-01-03 16:07 UTC by ToruiDev

2022-01-03 16:09 UTC, ToruiDev commented
This needs a review and testing online.
Maybe get like 2-3 People to test it out before sharing and merging it.

2022-01-09 17:11 UTC, Ekwav requested changes

2022-01-09 17:11 UTC, Ekwav commented on src/main/java/de/torui/coflsky/FlipHandler.java
> +				t.schedule(CurrentTask, 50 * 1000/* 30 seconds */ + /* small arbitrary delay */150);
move the seconds amount into a variable

2022-01-13 21:22 UTC, Ekwav requested changes

2022-01-13 21:22 UTC, Ekwav commented on src/main/java/de/torui/coflsky/WSCommandHandler.java
> +		flipHandler.fds.Insert(new de.torui.coflsky.FlipHandler.Flip(cmd.getData().Id, cmd.getData().Worth));
When holding the key down there is a noticeable delay between receiving flips (they even show up in chat) and the auction opening.
I am pretty sure that it is longer than my ping.
Could the opening be triggered in this method to optimise for opening auctions faster as it is very important

2022-01-18 21:44 UTC, Ekwav requested changes
Please send the command `track ("bestHotkey {uuid}")` when the hotkey event triggers

2022-01-24 18:57 UTC, Ekwav requested changes

2022-01-24 18:57 UTC, Ekwav commented on src/main/java/de/torui/coflsky/network/WSClient.java
> +
```suggestion

```

2022-01-24 18:59 UTC, Ekwav approved these changes
LGTM! :)

2022-01-24 19:00 UTC, merged