Add Auto-Toggle
Coflnet/SkyblockMod pull request #58
Opened 2022-05-07 14:37 UTC by HackedOS

2022-05-08 11:08 UTC, Ekwav approved these changes

2022-05-08 11:40 UTC, HackedOS commented
Closes https://github.com/Coflnet/SkyblockMod/issues/39

2022-05-09 18:48 UTC, HackedOS commented
Closes https://github.com/Coflnet/SkyblockMod/issues/43

2022-05-10 20:22 UTC, Ekwav requested changes

2022-05-10 20:22 UTC, Ekwav commented on src/main/java/de/torui/coflsky/EventRegistry.java
> +			ScoreboardData();
Run this on the thread pool as well

2022-05-10 20:22 UTC, Ekwav commented on src/main/java/de/torui/coflsky/EventRegistry.java
> +				Pattern pattern = Pattern.compile(Configuration.getInstance().chatRegex, Pattern.CASE_INSENSITIVE);
Please avoid recompilation by reusing the pattern

2022-05-12 15:14 UTC, Ekwav commented on src/main/java/de/torui/coflsky/EventRegistry.java
> +	Pattern chatpattern = Pattern.compile(Configuration.getInstance().chatRegex, Pattern.CASE_INSENSITIVE);
problem is that this doesn't refresh now anymore.  
It should be compiled when loaded and when `privacySettings` is called from the server

2022-05-12 16:41 UTC, Ekwav approved these changes

2022-05-12 16:41 UTC, merged