Add Proxy support to the cofl mod
Coflnet/SkyblockMod pull request #85
Opened 2023-01-25 16:47 UTC by abhithedev200

2023-01-25 16:48 UTC, abhithedev200 commented
this pr is not finished yet just implemented the basic proxy functionality with high-performance improvements

2023-01-25 18:34 UTC, abhithedev200 commented
Finished everything, now the pull request is ready for review!

2023-01-26 10:57 UTC, Ekwav requested changes

2023-01-26 10:57 UTC, Ekwav commented on src/main/java/de/torui/coflsky/proxy/ProxyManager.java
> +        }
```suggestion
         CompletableFuture<String> req = this.doRequest(request.getUrl());
        if(request.isUploadEnabled()) {
            req.thenAcceptAsync(res -> this.uploadData(res,request.getId()));
        }
```
The request should be made when its requested just not uploaded

2023-01-26 16:04 UTC, Ekwav approved these changes

2023-01-26 16:04 UTC, merged